### ISSUE TITLE
Non-functional Theme Toggle

### ISSUE THREAD

**Issue by ly-nld** [one-among-us/TransAcademicUniGuide#29]
The "👁" button is non-functional.
```html
<button onclick="toggle()">👁</button>
```

The code from @sauricat 's layout that is used: 
https://github.com/one-among-us/hugo-theme-book-oau/blob/6628d0da69dac16521db975a3067c7c149b8ebdc/layouts/_default/baseof.html#L105

The function tries to set the theme to `dark-mode` while already in `dark-mode`.
## GIF to demonstrate:
![gif](https://i.gyazo.com/24daf24d0b5dbdf112faf21da95979e4.gif)

I am not sure if the theme toggle() was supposed to be removed or if it was never properly implemented to switch to `white-mode`.

**Comment by sauricat** [comment]
I made a mistake. Will fix.
